"""create all base model

Revision ID: 7a97e0714e8c
Revises: dcb46907911c
Create Date: 2026-04-12 16:28:59.656365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a97e0714e8c'
down_revision: Union[str, Sequence[str], None] = 'dcb46907911c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False), schema='ecom_product')
    op.add_column('product', sa.Column('brand', sa.String(length=255), nullable=False), schema='ecom_product')
    op.add_column('product', sa.Column('category', sa.String(length=255), nullable=False), schema='ecom_product')
    op.add_column('product', sa.Column('status', sa.String(length=50), nullable=False), schema='ecom_product')
    op.add_column('product', sa.Column('llm_spec_text', sa.Text(), nullable=True), schema='ecom_product')
    op.add_column('product', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='ecom_product')
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True,
               schema='ecom_product')
    op.create_index('ix_product_created_at', 'product', ['created_at'], unique=False, schema='ecom_product')
    op.drop_column('product', 'price', schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False), schema='ecom_product')
    op.drop_index('ix_product_created_at', table_name='product', schema='ecom_product')
    op.alter_column('product', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               schema='ecom_product')
    op.drop_column('product', 'created_at', schema='ecom_product')
    op.drop_column('product', 'llm_spec_text', schema='ecom_product')
    op.drop_column('product', 'status', schema='ecom_product')
    op.drop_column('product', 'category', schema='ecom_product')
    op.drop_column('product', 'brand', schema='ecom_product')
    op.drop_column('product', 'base_price', schema='ecom_product')
    # ### end Alembic commands ###
