"""update user

Revision ID: 17ebfcaa3d22
Revises: 0ec6a9093844
Create Date: 2026-04-20 22:34:46.875790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ebfcaa3d22'
down_revision: Union[str, Sequence[str], None] = '0ec6a9093844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE ecom_client.userstatusenum AS ENUM (
            'ACTIVE',
            'INACTIVE',
            'EXPIRED',
            'PENDING',
            'DEACTIVATED',
            'NEW'
        );
        """
    )
    op.add_column('profile', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'NEW', name='userstatusenum', schema='ecom_client'), nullable=False), schema='ecom_client')
    op.add_column('profile_status', sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'NEW', name='userstatusenum', schema='ecom_client'), nullable=False), schema='ecom_client')
    op.add_column('profile_status', sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'NEW', name='userstatusenum', schema='ecom_client'), nullable=False), schema='ecom_client')
    op.add_column('user', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'NEW', name='userstatusenum', schema='ecom_client'), nullable=False), schema='ecom_client')
    op.add_column('user_status', sa.Column('src_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'NEW', name='userstatusenum', schema='ecom_client'), nullable=False), schema='ecom_client')
    op.add_column('user_status', sa.Column('dst_state', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'NEW', name='userstatusenum', schema='ecom_client'), nullable=False), schema='ecom_client')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_status', 'dst_state', schema='ecom_client')
    op.drop_column('user_status', 'src_state', schema='ecom_client')
    op.drop_column('user', 'status', schema='ecom_client')
    op.drop_column('profile_status', 'dst_state', schema='ecom_client')
    op.drop_column('profile_status', 'src_state', schema='ecom_client')
    op.drop_column('profile', 'status', schema='ecom_client')
    op.execute(
        """
        DROP TYPE IF EXISTS ecom_client.userstatusenum;
        """
    )
    # ### end Alembic commands ###
