"""ecom_discuss: update customer_review_tag

Revision ID: 52aead75ced9
Revises: c12615334c7d
Create Date: 2026-06-21 15:54:24.793463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52aead75ced9'
down_revision: Union[str, Sequence[str], None] = 'c12615334c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'customer_review_tag', 'comment', ['review_id'], ['_id'], source_schema='ecom_discuss', referent_schema='ecom_discuss', ondelete='CASCADE')
    op.add_column('review_tag_group', sa.Column('category_id', sa.UUID(), nullable=False), schema='ecom_discuss')
    op.create_index('idx_review_tag_group_category', 'review_tag_group', ['category_id'], unique=False, schema='ecom_discuss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_tag_group_category', table_name='review_tag_group', schema='ecom_discuss')
    op.drop_column('review_tag_group', 'category_id', schema='ecom_discuss')
    op.drop_constraint(None, 'customer_review_tag', schema='ecom_discuss', type_='foreignkey')
    # ### end Alembic commands ###
