"""update conversation context snapshot

Revision ID: f0bf44256a2d
Revises: 34180a82da35
Create Date: 2026-06-17 02:06:14.943052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0bf44256a2d'
down_revision: Union[str, Sequence[str], None] = '34180a82da35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_context_snapshot', 'other_filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_comment="Flexible extra constraints e.g. {os: 'Android', screen_size: '6inch+'}",
               schema='ecom_message')
    op.drop_constraint(op.f('conversation_context_snapshot_message_id_fkey'), 'conversation_context_snapshot', schema='ecom_message', type_='foreignkey')
    op.drop_column('conversation_context_snapshot', 'message_id', schema='ecom_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_context_snapshot', sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False, comment='The message that triggered this snapshot'), schema='ecom_message')
    op.create_foreign_key(op.f('conversation_context_snapshot_message_id_fkey'), 'conversation_context_snapshot', 'message', ['message_id'], ['_id'], source_schema='ecom_message', referent_schema='ecom_message', ondelete='CASCADE')
    op.alter_column('conversation_context_snapshot', 'other_filters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_comment="Flexible extra constraints e.g. {os: 'Android', screen_size: '6inch+'}",
               schema='ecom_message')
    # ### end Alembic commands ###
