"""update product

Revision ID: 5a171548380a
Revises: 17ebfcaa3d22
Create Date: 2026-04-23 23:57:01.302729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a171548380a'
down_revision: Union[str, Sequence[str], None] = '17ebfcaa3d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.UUID(), nullable=False), schema='ecom_product')
    op.create_foreign_key(None, 'product', 'product_category', ['category_id'], ['_id'], source_schema='ecom_product', referent_schema='ecom_product')
    op.drop_column('product', 'category', schema='ecom_product')
    op.drop_constraint(op.f('uq_product_category_name'), 'product_category', schema='ecom_product', type_='unique')
    op.create_foreign_key(None, 'product_spec_value', 'product', ['product_id'], ['_id'], source_schema='ecom_product', referent_schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_spec_value', schema='ecom_product', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_product_category_name'), 'product_category', ['name'], schema='ecom_product')
    op.add_column('product', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='ecom_product')
    op.drop_constraint(None, 'product', schema='ecom_product', type_='foreignkey')
    op.drop_column('product', 'category_id', schema='ecom_product')
    # ### end Alembic commands ###
