"""recreate message schema

Revision ID: cd9474131bf5
Revises: a92a2a44e7c6
Create Date: 2026-06-10 17:34:19.419635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd9474131bf5'
down_revision: Union[str, Sequence[str], None] = 'a92a2a44e7c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

conversation_status_enum = postgresql.ENUM(
    'active',
    'archived',
    'deleted',
    name='conversationstatusenum',
    schema='ecom_message',
    create_type=True
)

message_intent_enum = postgresql.ENUM(
    'product_search',
    'compare',
    'clarify',
    'smalltalk',
    name='messageintentenum',
    schema='ecom_message',
    create_type=True
)

message_role_enum = postgresql.ENUM(
    'user', 
    'assistant', 
    'system',
    name='messageroleenum',
    schema='ecom_message',
    create_type=True
)



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()

    conversation_status_enum.create(
        bind,
        checkfirst=True
    )

    message_intent_enum.create(
        bind,
        checkfirst=True
    )

    message_role_enum.create(
        bind, 
        checkfirst=True
    )
    
    op.create_table('chat_context_snapshot',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='The message that triggered this snapshot'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Product category extracted from context e.g. mobile, laptop'),
    sa.Column('use_case', sa.String(length=100), nullable=True, comment='Intended use case e.g. gaming, photography, business'),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('preferred_brands', postgresql.ARRAY(sa.String()), nullable=True, comment="e.g. ['Samsung', 'Apple']"),
    sa.Column('other_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Flexible extra constraints e.g. {os: 'Android', screen_size: '6inch+'}"),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ecom_message.conversation._id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ecom_message.message._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_message'
    )
    op.create_index(op.f('ix_ecom_message_chat_context_snapshot_conversation_id'), 'chat_context_snapshot', ['conversation_id'], unique=False, schema='ecom_message')
    op.create_table('recommendation',
    sa.Column('message_id', sa.UUID(), nullable=False, comment='The assistant message that delivered this recommendation'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Denormalized for fast conversation-level queries'),
    sa.Column('strategy', sa.Enum('rule_based', 'ai_ranked', 'hybrid', name='recommendationstrategyenum', schema='ecom_message'), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['ecom_message.message._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('message_id'),
    schema='ecom_message'
    )
    op.create_index(op.f('ix_ecom_message_recommendation_conversation_id'), 'recommendation', ['conversation_id'], unique=False, schema='ecom_message')
    op.create_table('recommendation_item',
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False, comment='1 = top pick within this recommendation'),
    sa.Column('score', sa.Float(), nullable=True, comment='Relevance score from 0.0 to 1.0'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Explanation shown to user e.g. "Matches gaming use case, within $500 budget"'),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ecom_message.recommendation._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_message'
    )
    op.create_index(op.f('ix_ecom_message_recommendation_item_recommendation_id'), 'recommendation_item', ['recommendation_id'], unique=False, schema='ecom_message')
    op.create_table('recommendation_feedback',
    sa.Column('recommendation_item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Reference to identity context — no FK across bounded contexts'),
    sa.Column('action', sa.Enum('viewed', 'clicked', 'purchased', 'dismissed', 'helpful', 'not_helpful', name='feedbackactionenum', schema='ecom_message'), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['ecom_message.recommendation_item._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_message'
    )
    op.create_index(op.f('ix_ecom_message_recommendation_feedback_recommendation_item_id'), 'recommendation_feedback', ['recommendation_item_id'], unique=False, schema='ecom_message')
    op.add_column('conversation', sa.Column('title', sa.String(length=255), nullable=True, comment='Auto-generated from first message snippet or user-renamed'), schema='ecom_message')
    op.add_column('conversation', sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='conversationstatusenum', schema='ecom_message'), nullable=False), schema='ecom_message')
    op.add_column('conversation', sa.Column('version', sa.Integer(), nullable=False, comment='Optimistic locking — increment on each state change'), schema='ecom_message')
    op.alter_column('conversation', 'user_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Reference to identity context — no FK across bounded contexts',
               schema='ecom_message')
    op.drop_index(op.f('ix_conversation_created_at'), table_name='conversation', schema='ecom_message')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation', schema='ecom_message')
    op.create_index(op.f('ix_ecom_message_conversation_user_id'), 'conversation', ['user_id'], unique=False, schema='ecom_message')
    op.drop_column('conversation', 'created_at', schema='ecom_message')
    op.drop_column('conversation', 'session_id', schema='ecom_message')
    op.add_column('message', sa.Column('sequence_number', sa.Integer(), nullable=False, comment='Ordering of messages within a conversation'), schema='ecom_message')
    op.add_column('message', sa.Column('intent', sa.Enum('product_search', 'compare', 'clarify', 'smalltalk', name='messageintentenum', schema='ecom_message'), nullable=True, comment='Classified intent — only populated for user role messages'), schema='ecom_message')
    op.alter_column(
        'message',
        'role',
        existing_type=sa.VARCHAR(length=50),
        type_=message_role_enum,
        existing_nullable=False,
        postgresql_using=
        'role::ecom_message.messageroleenum',
        schema='ecom_message'
    )
    op.alter_column('message', 'content',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='Raw text content of the message',
               schema='ecom_message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message', schema='ecom_message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message', schema='ecom_message')
    op.create_index(op.f('ix_ecom_message_message_conversation_id'), 'message', ['conversation_id'], unique=False, schema='ecom_message')
    op.drop_constraint(op.f('message_conversation_id_fkey'), 'message', schema='ecom_message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['_id'], source_schema='ecom_message', referent_schema='ecom_message', ondelete='CASCADE')
    op.drop_column('message', 'status', schema='ecom_message')
    op.drop_column('message', 'message_type', schema='ecom_message')
    op.drop_column('message', 'created_at', schema='ecom_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='ecom_message')
    op.add_column('message', sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='ecom_message')
    op.add_column('message', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='ecom_message')
    op.drop_constraint(None, 'message', schema='ecom_message', type_='foreignkey')
    op.create_foreign_key(op.f('message_conversation_id_fkey'), 'message', 'conversation', ['conversation_id'], ['_id'], source_schema='ecom_message', referent_schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_message_conversation_id'), table_name='message', schema='ecom_message')
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False, schema='ecom_message')
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False, schema='ecom_message')
    op.alter_column('message', 'content',
               existing_type=sa.TEXT(),
               nullable=False,
               comment=None,
               existing_comment='Raw text content of the message',
               schema='ecom_message')
    op.alter_column('message', 'role',
               existing_type=sa.Enum('user', 'assistant', 'system', name='messageroleenum', schema='ecom_message'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='ecom_message')
    op.drop_column('message', 'intent', schema='ecom_message')
    op.drop_column('message', 'sequence_number', schema='ecom_message')
    op.add_column('conversation', sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='ecom_message')
    op.add_column('conversation', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_conversation_user_id'), table_name='conversation', schema='ecom_message')
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False, schema='ecom_message')
    op.create_index(op.f('ix_conversation_created_at'), 'conversation', ['created_at'], unique=False, schema='ecom_message')
    op.alter_column('conversation', 'user_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment=None,
               existing_comment='Reference to identity context — no FK across bounded contexts',
               schema='ecom_message')
    op.drop_column('conversation', 'version', schema='ecom_message')
    op.drop_column('conversation', 'status', schema='ecom_message')
    op.drop_column('conversation', 'title', schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_recommendation_feedback_recommendation_item_id'), table_name='recommendation_feedback', schema='ecom_message')
    op.drop_table('recommendation_feedback', schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_recommendation_item_recommendation_id'), table_name='recommendation_item', schema='ecom_message')
    op.drop_table('recommendation_item', schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_recommendation_conversation_id'), table_name='recommendation', schema='ecom_message')
    op.drop_table('recommendation', schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_chat_context_snapshot_conversation_id'), table_name='chat_context_snapshot', schema='ecom_message')
    op.drop_table('chat_context_snapshot', schema='ecom_message')
    # ### end Alembic commands ###
