"""delete table promotion and customer_review

Revision ID: ed5a50d7e956
Revises: 30545b44c81f
Create Date: 2026-05-07 16:51:48.177073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed5a50d7e956'
down_revision: Union[str, Sequence[str], None] = '30545b44c81f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_review', schema='ecom_product')
    op.drop_table('promotion', schema='ecom_product')
    # op.alter_column('product', 'brand_id',
    #            existing_type=sa.UUID(),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product', 'slug',
    #            existing_type=sa.VARCHAR(length=500),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_brand', 'slug',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_category', 'slug',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_image', 'sort_order',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_line', 'slug',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'product_spec_group_id',
    #            existing_type=sa.UUID(),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'key',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'label',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'is_filterable',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'sort_order',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            schema='ecom_product')
    # op.alter_column('product_variant', 'status',
    #            existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', name='productvariantstatusenum', schema='ecom_product'),
    #            nullable=False,
    #            schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('product_variant', 'status',
    #            existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', name='productvariantstatusenum', schema='ecom_product'),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'sort_order',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'is_filterable',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'label',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'key',
    #            existing_type=sa.VARCHAR(length=100),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_spec_value', 'product_spec_group_id',
    #            existing_type=sa.UUID(),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_line', 'slug',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_image', 'sort_order',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_category', 'slug',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product_brand', 'slug',
    #            existing_type=sa.VARCHAR(length=255),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product', 'slug',
    #            existing_type=sa.VARCHAR(length=500),
    #            nullable=True,
    #            schema='ecom_product')
    # op.alter_column('product', 'brand_id',
    #            existing_type=sa.UUID(),
    #            nullable=True,
    #            schema='ecom_product')
    op.create_table('promotion',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gift', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('_realm', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('_creator', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('_updater', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('_deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('_etag', sa.VARCHAR(length=64), server_default=sa.text('(uuid_generate_v4())::character varying'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_product.product._id'], name=op.f('promotion_product_id_fkey')),
    sa.PrimaryKeyConstraint('_id', name=op.f('promotion_pkey')),
    schema='ecom_product'
    )
    op.create_table('customer_review',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('_realm', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('_creator', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('_updater', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('_deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('_etag', sa.VARCHAR(length=64), server_default=sa.text('(uuid_generate_v4())::character varying'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_product.product._id'], name=op.f('customer_review_product_id_fkey')),
    sa.PrimaryKeyConstraint('_id', name=op.f('customer_review_pkey')),
    schema='ecom_product'
    )
    # ### end Alembic commands ###
