"""update table spec group

Revision ID: fdb04f39fa6d
Revises: 3b09cca3f7f1
Create Date: 2026-04-29 13:49:13.203158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb04f39fa6d'
down_revision: Union[str, Sequence[str], None] = '3b09cca3f7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spec_group', sa.Column('category_id', sa.UUID(), nullable=True), schema='ecom_product')
    op.drop_index(op.f('ix_spec_group_category'), table_name='spec_group', schema='ecom_product')
    op.create_index('ix_spec_group_category_id', 'spec_group', ['category_id'], unique=False, schema='ecom_product')
    op.create_foreign_key(None, 'spec_group', 'product_category', ['category_id'], ['_id'], source_schema='ecom_product', referent_schema='ecom_product')
    op.drop_column('spec_group', 'category', schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spec_group', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True), schema='ecom_product')
    op.drop_constraint(None, 'spec_group', schema='ecom_product', type_='foreignkey')
    op.drop_index('ix_spec_group_category_id', table_name='spec_group', schema='ecom_product')
    op.create_index(op.f('ix_spec_group_category'), 'spec_group', ['category'], unique=False, schema='ecom_product')
    op.drop_column('spec_group', 'category_id', schema='ecom_product')
    # ### end Alembic commands ###
