"""create table view for category in product

Revision ID: 2f618ed284cc
Revises: e10af7acec0e
Create Date: 2026-05-01 15:41:12.298794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '2f618ed284cc'
down_revision: Union[str, Sequence[str], None] = 'e10af7acec0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ecom_product__product_category_list = PGView(
        schema="ecom_product",
        signature="_product_category_list",
        definition='SELECT\n        pc._id,\n        pc._created,\n        pc._updated,\n        pc._creator,\n        pc._updater,\n        pc._deleted,\n        pc._etag,\n        pc._realm,\n        pc.name,\n        pc.description,\n        COUNT(DISTINCT pl.brand_id)                         AS brand_count,\n        COALESCE(\n            array_agg(DISTINCT pb.name) FILTER (WHERE pb.name IS NOT NULL),\n            ARRAY[]::varchar[]\n        )                                                   AS brand_names\n    FROM "ecom_product".product_category AS pc\n    LEFT JOIN "ecom_product".product_line AS pl\n        ON pl.category_id = pc._id\n        AND pl._deleted IS NULL\n    LEFT JOIN "ecom_product".product_brand AS pb\n        ON pb._id = pl.brand_id\n        AND pb._deleted IS NULL\n    WHERE pc._deleted IS NULL\n    GROUP BY\n        pc._id,\n        pc._created,\n        pc._updated,\n        pc._creator,\n        pc._updater,\n        pc._deleted,\n        pc._etag,\n        pc._realm,\n        pc.name,\n        pc.description,\n        pc._realm\n    ORDER BY pc.name'
    )
    op.create_entity(ecom_product__product_category_list)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    ecom_product__product_category_list = PGView(
        schema="ecom_product",
        signature="_product_category_list",
        definition='SELECT\n        pc._id,\n        pc._created,\n        pc._updated,\n        pc._creator,\n        pc._updater,\n        pc._deleted,\n        pc._etag,\n        pc._realm,\n        pc.name,\n        pc.description,\n        COUNT(DISTINCT pl.brand_id)                         AS brand_count,\n        COALESCE(\n            array_agg(DISTINCT pb.name) FILTER (WHERE pb.name IS NOT NULL),\n            ARRAY[]::varchar[]\n        )                                                   AS brand_names\n    FROM "ecom_product".product_category AS pc\n    LEFT JOIN "ecom_product".product_line AS pl\n        ON pl.category_id = pc._id\n        AND pl._deleted IS NULL\n    LEFT JOIN "ecom_product".product_brand AS pb\n        ON pb._id = pl.brand_id\n        AND pb._deleted IS NULL\n    WHERE pc._deleted IS NULL\n    GROUP BY\n        pc._id,\n        pc._created,\n        pc._updated,\n        pc._creator,\n        pc._updater,\n        pc._deleted,\n        pc._etag,\n        pc._realm,\n        pc.name,\n        pc.description,\n        pc._realm\n    ORDER BY pc.name'
    )
    op.drop_entity(ecom_product__product_category_list)

    # ### end Alembic commands ###
