"""upgrade user

Revision ID: 7a1e0b9ca9b2
Revises: 7a97e0714e8c
Create Date: 2026-04-12 17:49:22.609603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a1e0b9ca9b2'
down_revision: Union[str, Sequence[str], None] = '7a97e0714e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type only if it doesn't exist using PostgreSQL DO block
    op.execute("""
    DO $$ BEGIN
        CREATE TYPE ecom_client.userstatusenum AS ENUM (
            'ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING', 'DEACTIVATED', 'NEW'
        );
    EXCEPTION
        WHEN duplicate_object THEN null;
    END $$;
    """)
    op.create_table('profile_role',
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('role_key', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('role_source', sa.String(length=255), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['ecom_client.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_client'
    )
    op.create_table('profile_status',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('src_state', sa.String(length=50), nullable=False),
    sa.Column('dst_state', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['ecom_client.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_client'
    )
    op.add_column('profile', sa.Column('access_tags', sa.ARRAY(sa.String()), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('active', sa.Boolean(), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('address', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('picture_id', sa.UUID(), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('birthdate', sa.DateTime(timezone=True), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('gender', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('language', sa.ARRAY(sa.String()), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('name__family', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('name__given', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('name__middle', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('name__prefix', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('name__suffix', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('telecom__email', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('telecom__phone', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('tfa_method', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('tfa_token', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('two_factor_authentication', sa.Boolean(), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('upstream_user_id', sa.UUID(), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('user_type', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('username', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('verified_email', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('verified_phone', sa.String(length=1024), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('primary_language', sa.String(length=255), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('is_super_admin', sa.Boolean(), nullable=True), schema='ecom_client')
    op.add_column(
        'profile',
        sa.Column('status', sa.String(length=50), nullable=False),
        schema='ecom_client'
    )    
    op.add_column('profile', sa.Column('preferred_name', sa.String(length=255), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('default_theme', sa.String(length=255), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('user_id', sa.UUID(), nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('current_profile', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='ecom_client')
    op.drop_index(op.f('ix_profile_email'), table_name='profile', schema='ecom_client')
    op.drop_constraint(op.f('profile_email_key'), 'profile', schema='ecom_client', type_='unique')
    op.create_foreign_key(None, 'profile', 'user', ['user_id'], ['_id'], source_schema='ecom_client', referent_schema='ecom_client')
    op.drop_column('profile', 'created_at', schema='ecom_client')
    op.drop_column('profile', 'full_name', schema='ecom_client')
    op.drop_column('profile', 'email', schema='ecom_client')
    op.drop_column('profile', 'role', schema='ecom_client')
    op.drop_column('user', 'name__prefix', schema='ecom_client')
    op.drop_column('user', 'name__given', schema='ecom_client')
    op.drop_column('user', 'telecom__phone', schema='ecom_client')
    op.drop_column('user', 'name__middle', schema='ecom_client')
    op.drop_column('user', 'name__suffix', schema='ecom_client')
    op.drop_column('user', 'verified_phone', schema='ecom_client')
    op.drop_column('user', 'verified_email', schema='ecom_client')
    op.drop_column('user', 'realm_access', schema='ecom_client')
    op.drop_column('user', 'name__family', schema='ecom_client')
    op.drop_column('user', 'telecom__email', schema='ecom_client')
    op.drop_column('user', 'resource_access', schema='ecom_client')
    op.add_column('user_identity', sa.Column('password_hash', sa.String(length=255), nullable=True), schema='ecom_client')
    
    op.execute("""
    ALTER TABLE ecom_client.profile_status
    ALTER COLUMN src_state TYPE ecom_client.userstatusenum
    USING src_state::text::ecom_client.userstatusenum;
    """)

    op.execute("""
    ALTER TABLE ecom_client.profile_status
    ALTER COLUMN dst_state TYPE ecom_client.userstatusenum
    USING dst_state::text::ecom_client.userstatusenum;
    """)

    op.execute("""
    ALTER TABLE ecom_client.profile
    ALTER COLUMN status TYPE ecom_client.userstatusenum
    USING status::text::ecom_client.userstatusenum;
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_identity', 'password_hash', schema='ecom_client')
    op.add_column('user', sa.Column('resource_access', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('telecom__email', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('name__family', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('realm_access', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('verified_email', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('verified_phone', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('name__suffix', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('name__middle', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('telecom__phone', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('name__given', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('user', sa.Column('name__prefix', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='ecom_client')
    op.add_column('profile', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='ecom_client')
    op.add_column('profile', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='ecom_client')
    op.add_column('profile', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='ecom_client')
    op.add_column('profile', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False), schema='ecom_client')
    op.drop_constraint(None, 'profile', schema='ecom_client', type_='foreignkey')
    op.create_unique_constraint(op.f('profile_email_key'), 'profile', ['email'], schema='ecom_client')
    op.create_index(op.f('ix_profile_email'), 'profile', ['email'], unique=False, schema='ecom_client')
    op.drop_column('profile', 'current_profile', schema='ecom_client')
    op.drop_column('profile', 'user_id', schema='ecom_client')
    op.drop_column('profile', 'default_theme', schema='ecom_client')
    op.drop_column('profile', 'preferred_name', schema='ecom_client')
    op.drop_column('profile', 'status', schema='ecom_client')
    op.drop_column('profile', 'is_super_admin', schema='ecom_client')
    op.drop_column('profile', 'last_sync', schema='ecom_client')
    op.drop_column('profile', 'primary_language', schema='ecom_client')
    op.drop_column('profile', 'verified_phone', schema='ecom_client')
    op.drop_column('profile', 'verified_email', schema='ecom_client')
    op.drop_column('profile', 'username', schema='ecom_client')
    op.drop_column('profile', 'user_type', schema='ecom_client')
    op.drop_column('profile', 'upstream_user_id', schema='ecom_client')
    op.drop_column('profile', 'two_factor_authentication', schema='ecom_client')
    op.drop_column('profile', 'tfa_token', schema='ecom_client')
    op.drop_column('profile', 'tfa_method', schema='ecom_client')
    op.drop_column('profile', 'telecom__phone', schema='ecom_client')
    op.drop_column('profile', 'telecom__email', schema='ecom_client')
    op.drop_column('profile', 'name__suffix', schema='ecom_client')
    op.drop_column('profile', 'name__prefix', schema='ecom_client')
    op.drop_column('profile', 'name__middle', schema='ecom_client')
    op.drop_column('profile', 'name__given', schema='ecom_client')
    op.drop_column('profile', 'name__family', schema='ecom_client')
    op.drop_column('profile', 'last_login', schema='ecom_client')
    op.drop_column('profile', 'language', schema='ecom_client')
    op.drop_column('profile', 'gender', schema='ecom_client')
    op.drop_column('profile', 'expiration_date', schema='ecom_client')
    op.drop_column('profile', 'birthdate', schema='ecom_client')
    op.drop_column('profile', 'picture_id', schema='ecom_client')
    op.drop_column('profile', 'address', schema='ecom_client')
    op.drop_column('profile', 'active', schema='ecom_client')
    op.drop_column('profile', 'access_tags', schema='ecom_client')
    op.drop_table('profile_status', schema='ecom_client')
    op.drop_table('profile_role', schema='ecom_client')
    
    # Drop ENUM type if it exists
    op.execute("""
        DROP TYPE IF EXISTS ecom_client.userstatusenum CASCADE;
    """)
    # ### end Alembic commands ###
