"""recreate conversation context snapshot

Revision ID: 34180a82da35
Revises: cd9474131bf5
Create Date: 2026-06-17 02:03:18.849397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34180a82da35'
down_revision: Union[str, Sequence[str], None] = 'cd9474131bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_context_snapshot',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False, comment='The message that triggered this snapshot'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Product category extracted from context e.g. mobile, laptop'),
    sa.Column('use_case', sa.String(length=100), nullable=True, comment='Intended use case e.g. gaming, photography, business'),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('preferred_brands', postgresql.ARRAY(sa.String()), nullable=True, comment="e.g. ['Samsung', 'Apple']"),
    sa.Column('other_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Flexible extra constraints e.g. {os: 'Android', screen_size: '6inch+'}"),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ecom_message.conversation._id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ecom_message.message._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_message'
    )
    op.create_index(op.f('ix_ecom_message_conversation_context_snapshot_conversation_id'), 'conversation_context_snapshot', ['conversation_id'], unique=False, schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_chat_context_snapshot_conversation_id'), table_name='chat_context_snapshot', schema='ecom_message')
    op.drop_table('chat_context_snapshot', schema='ecom_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_context_snapshot',
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False, comment='The message that triggered this snapshot'),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Product category extracted from context e.g. mobile, laptop'),
    sa.Column('use_case', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Intended use case e.g. gaming, photography, business'),
    sa.Column('budget_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('budget_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('preferred_brands', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True, comment="e.g. ['Samsung', 'Apple']"),
    sa.Column('other_filters', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment="Flexible extra constraints e.g. {os: 'Android', screen_size: '6inch+'}"),
    sa.Column('_realm', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('_creator', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('_updater', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('_deleted', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('_etag', sa.VARCHAR(length=64), server_default=sa.text('(uuid_generate_v4())::character varying'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ecom_message.conversation._id'], name=op.f('chat_context_snapshot_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ecom_message.message._id'], name=op.f('chat_context_snapshot_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id', name=op.f('chat_context_snapshot_pkey')),
    schema='ecom_message'
    )
    op.create_index(op.f('ix_ecom_message_chat_context_snapshot_conversation_id'), 'chat_context_snapshot', ['conversation_id'], unique=False, schema='ecom_message')
    op.drop_index(op.f('ix_ecom_message_conversation_context_snapshot_conversation_id'), table_name='conversation_context_snapshot', schema='ecom_message')
    op.drop_table('conversation_context_snapshot', schema='ecom_message')
    # ### end Alembic commands ###
