"""update product

Revision ID: 3b09cca3f7f1
Revises: 6fda39faccdc
Create Date: 2026-04-28 22:12:22.395483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b09cca3f7f1'
down_revision: Union[str, Sequence[str], None] = '6fda39faccdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_brand',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product'
    )
    op.create_table('product_line',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['ecom_product.product_brand._id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['ecom_product.product_category._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product'
    )
    op.create_table('customer_review',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_product.product._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product'
    )
    op.create_table('promotion',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('gift', sa.String(length=255), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_product.product._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product'
    )
    op.add_column('product', sa.Column('line_id', sa.UUID(), nullable=False), schema='ecom_product')
    op.drop_constraint(op.f('product_category_id_fkey'), 'product', schema='ecom_product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'product_line', ['line_id'], ['_id'], source_schema='ecom_product', referent_schema='ecom_product')
    op.drop_column('product', 'category_id', schema='ecom_product')
    op.drop_column('product', 'brand', schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='ecom_product')
    op.add_column('product', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False), schema='ecom_product')
    op.drop_constraint(None, 'product', schema='ecom_product', type_='foreignkey')
    op.create_foreign_key(op.f('product_category_id_fkey'), 'product', 'product_category', ['category_id'], ['_id'], source_schema='ecom_product', referent_schema='ecom_product')
    op.drop_column('product', 'line_id', schema='ecom_product')
    op.drop_table('promotion', schema='ecom_product')
    op.drop_table('customer_review', schema='ecom_product')
    op.drop_table('product_line', schema='ecom_product')
    op.drop_table('product_brand', schema='ecom_product')
    # ### end Alembic commands ###
