"""create ecom_discuss

Revision ID: c12615334c7d
Revises: 1a73d75d8201
Create Date: 2026-06-19 21:51:57.494738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12615334c7d'
down_revision: Union[str, Sequence[str], None] = '1a73d75d8201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure schema exists before creating types/tables in it
    op.execute("CREATE SCHEMA IF NOT EXISTS ecom_discuss")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('resource_type', sa.Enum('PRODUCT', 'POST', name='resourcetypeenum', schema='ecom_discuss'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name_user', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.CheckConstraint('depth >= 0 AND depth <= 1', name='ck_comment_depth'),
    sa.CheckConstraint('star IS NULL OR (star >= 1 AND star <= 5)', name='ck_comment_star'),
    sa.ForeignKeyConstraint(['parent_id'], ['ecom_discuss.comment._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_discuss'
    )
    op.create_index('idx_comment_parent', 'comment', ['parent_id'], unique=False, schema='ecom_discuss')
    op.create_index('idx_comment_resource', 'comment', ['resource_type', 'resource_id'], unique=False, schema='ecom_discuss')
    op.create_index('idx_comment_user', 'comment', ['user_id'], unique=False, schema='ecom_discuss')
    op.create_table('review_tag_group',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_discuss'
    )
    op.create_table('comment_reaction',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction_type', sa.Enum('LIKE', 'LOVE', 'HAHA', 'SAD', 'WOW', 'ANGRY', name='reactiontypeenum', schema='ecom_discuss'), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['ecom_discuss.comment._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_reaction_user'),
    schema='ecom_discuss'
    )
    op.create_index('idx_comment_reaction_comment', 'comment_reaction', ['comment_id'], unique=False, schema='ecom_discuss')
    op.create_index('idx_comment_reaction_user', 'comment_reaction', ['user_id'], unique=False, schema='ecom_discuss')
    op.create_table('review_tag_option',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ecom_discuss.review_tag_group._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_discuss'
    )
    op.create_index('idx_review_tag_option_group', 'review_tag_option', ['group_id'], unique=False, schema='ecom_discuss')
    op.create_table('customer_review_tag',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['ecom_discuss.review_tag_option._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('review_id', 'option_id', name='uq_review_tag'),
    schema='ecom_discuss'
    )
    op.create_index('idx_customer_review_tag_review', 'customer_review_tag', ['review_id'], unique=False, schema='ecom_discuss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_customer_review_tag_review', table_name='customer_review_tag', schema='ecom_discuss')
    op.drop_table('customer_review_tag', schema='ecom_discuss')
    op.drop_index('idx_review_tag_option_group', table_name='review_tag_option', schema='ecom_discuss')
    op.drop_table('review_tag_option', schema='ecom_discuss')
    op.drop_index('idx_comment_reaction_user', table_name='comment_reaction', schema='ecom_discuss')
    op.drop_index('idx_comment_reaction_comment', table_name='comment_reaction', schema='ecom_discuss')
    op.drop_table('comment_reaction', schema='ecom_discuss')
    op.drop_table('review_tag_group', schema='ecom_discuss')
    op.drop_index('idx_comment_user', table_name='comment', schema='ecom_discuss')
    op.drop_index('idx_comment_resource', table_name='comment', schema='ecom_discuss')
    op.drop_index('idx_comment_parent', table_name='comment', schema='ecom_discuss')
    op.drop_table('comment', schema='ecom_discuss')
    # ### end Alembic commands ###
