"""create table product category

Revision ID: dcb46907911c
Revises: 04ef28542074
Create Date: 2026-04-09 22:12:48.848947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb46907911c'
down_revision: Union[str, Sequence[str], None] = '04ef28542074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product'
    )
    op.alter_column('product', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True,
               schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False,
               schema='ecom_product')
    op.drop_table('product_category', schema='ecom_product')
    # ### end Alembic commands ###
