"""create customer review and view

Revision ID: 9e0a19740a02
Revises: f0bf44256a2d
Create Date: 2026-06-18 16:47:06.676937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0a19740a02'
down_revision: Union[str, Sequence[str], None] = 'f0bf44256a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_review',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.CheckConstraint('depth >= 0 AND depth <= 1', name='ck_customer_review_depth'),
    sa.CheckConstraint('star >= 1 AND star <= 5', name='ck_customer_review_star'),
    sa.ForeignKeyConstraint(['parent_id'], ['ecom_product.customer_review._id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_product.product._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product'
    )
    op.create_index('idx_customer_review_parent', 'customer_review', ['parent_id'], unique=False, schema='ecom_product')
    op.create_index('idx_customer_review_product', 'customer_review', ['product_id'], unique=False, schema='ecom_product')
    op.create_index('idx_customer_review_user', 'customer_review', ['user_id'], unique=False, schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_customer_review_user', table_name='customer_review', schema='ecom_product')
    op.drop_index('idx_customer_review_product', table_name='customer_review', schema='ecom_product')
    op.drop_index('idx_customer_review_parent', table_name='customer_review', schema='ecom_product')
    op.drop_table('customer_review', schema='ecom_product')
    # ### end Alembic commands ###
