"""update table product_variant

Revision ID: 6181b29726e9
Revises: ed5a50d7e956
Create Date: 2026-05-07 22:02:57.166919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6181b29726e9'
down_revision: Union[str, Sequence[str], None] = 'ed5a50d7e956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product', 'slug',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_brand', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_image', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_line', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'product_spec_group_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'label',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'is_filterable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='ecom_product')
    op.add_column('product_variant', sa.Column('tag', sa.String(length=255), nullable=True), schema='ecom_product')
    op.alter_column('product_variant', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', name='productvariantstatusenum', schema='ecom_product'),
               nullable=False,
               schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variant', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', name='productvariantstatusenum', schema='ecom_product'),
               nullable=True,
               schema='ecom_product')
    op.drop_column('product_variant', 'tag', schema='ecom_product')
    op.alter_column('product_spec_value', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'is_filterable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'label',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_spec_value', 'product_spec_group_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_line', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_image', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product_brand', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product', 'slug',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               schema='ecom_product')
    op.alter_column('product', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='ecom_product')
    # ### end Alembic commands ###
