"""create product enum

Revision ID: 6fda39faccdc
Revises: 5a171548380a
Create Date: 2026-04-24 00:17:27.739677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fda39faccdc'
down_revision: Union[str, Sequence[str], None] = '5a171548380a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first in the ecom_product schema
    productstatusenum = sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', 'DISCONTINUED', 'ARCHIVED', name='productstatusenum', schema='ecom_product')
    spectypeenum = sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'JSON', 'SELECT', 'MULTISELECT', name='spectypeenum', schema='ecom_product')
    
    productstatusenum.create(op.get_bind(), checkfirst=True)
    spectypeenum.create(op.get_bind(), checkfirst=True)
    
    # Then alter columns to use the enum types
    op.alter_column('product', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', 'DISCONTINUED', 'ARCHIVED', name='productstatusenum', schema='ecom_product'),
               existing_nullable=False,
               schema='ecom_product',
               postgresql_using='status::ecom_product.productstatusenum')
    op.alter_column('spec_attribute', 'data_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'JSON', 'SELECT', 'MULTISELECT', name='spectypeenum', schema='ecom_product'),
               existing_nullable=False,
               schema='ecom_product',
               postgresql_using='data_type::ecom_product.spectypeenum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter columns back to VARCHAR first
    op.alter_column('spec_attribute', 'data_type',
               existing_type=sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'JSON', 'SELECT', 'MULTISELECT', name='spectypeenum', schema='ecom_product'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='ecom_product',
               postgresql_using='data_type::varchar')
    op.alter_column('product', 'status',
               existing_type=sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', 'DISCONTINUED', 'ARCHIVED', name='productstatusenum', schema='ecom_product'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='ecom_product',
               postgresql_using='status::varchar')
    
    # Then drop the enum types
    productstatusenum = sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'OUT_OF_STOCK', 'DISCONTINUED', 'ARCHIVED', name='productstatusenum', schema='ecom_product')
    spectypeenum = sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'JSON', 'SELECT', 'MULTISELECT', name='spectypeenum', schema='ecom_product')
    
    productstatusenum.drop(op.get_bind(), checkfirst=True)
    spectypeenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
