"""update product sale price

Revision ID: e10af7acec0e
Revises: fdb04f39fa6d
Create Date: 2026-04-30 16:15:35.097936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e10af7acec0e'
down_revision: Union[str, Sequence[str], None] = 'fdb04f39fa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_spec_value',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['ecom_product.spec_attribute._id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['ecom_product.product._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product'
    )
    op.create_index('ix_product_spec_value_attribute_id', 'product_spec_value', ['attribute_id'], unique=False, schema='ecom_product')
    op.create_index('ix_product_spec_value_product_id', 'product_spec_value', ['product_id'], unique=False, schema='ecom_product')
    op.add_column('product', sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True), schema='ecom_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'sale_price', schema='ecom_product')
    op.drop_index('ix_product_spec_value_product_id', table_name='product_spec_value', schema='ecom_product')
    op.drop_index('ix_product_spec_value_attribute_id', table_name='product_spec_value', schema='ecom_product')
    op.drop_table('product_spec_value', schema='ecom_product')
    # ### end Alembic commands ###
