"""add role and supplier_profile tables

Revision ID: 15e88d96de21
Revises: 0cc3dac71db6
Create Date: 2026-05-02 16:03:01.782274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e88d96de21'
down_revision: Union[str, Sequence[str], None] = '0cc3dac71db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('name'),
    schema='ecom_client'
    )
    op.create_table('_product_brand_line_list',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('line_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('line_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_etag', sa.String(length=64), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product',
    info={'is_view': True}
    )
    op.create_table('_product_category_list',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.String(length=255), nullable=True),
    sa.Column('_updater', sa.String(length=255), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('brand_count', sa.Integer(), nullable=False),
    sa.Column('brand_names', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product',
    info={'is_view': True}
    )
    op.create_table('_product_detail',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.String(length=255), nullable=True),
    sa.Column('_updater', sa.String(length=255), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('llm_spec_text', sa.String(), nullable=True),
    sa.Column('line_id', sa.UUID(), nullable=True),
    sa.Column('line_name', sa.String(length=255), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_description', sa.String(length=2048), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('variant_attributes', sa.JSON(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('gift', sa.Boolean(), nullable=True),
    sa.Column('promo_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promo_valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('images', sa.ARRAY(sa.JSON()), nullable=True),
    sa.Column('specs_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product',
    info={'is_view': True}
    )
    op.create_table('_product_list',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.String(length=255), nullable=True),
    sa.Column('_updater', sa.String(length=255), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('line_id', sa.UUID(), nullable=True),
    sa.Column('line_name', sa.String(length=255), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('gift', sa.Boolean(), nullable=True),
    sa.Column('promo_valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promo_valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_image_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product',
    info={'is_view': True}
    )
    op.create_table('_product_review_list',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.String(length=255), nullable=True),
    sa.Column('_updater', sa.String(length=255), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=4096), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product',
    info={'is_view': True}
    )
    op.create_table('_product_spec_detail',
    sa.Column('_id', sa.UUID(), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), nullable=True),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('group_sort_order', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('attribute_id', sa.UUID(), nullable=True),
    sa.Column('attribute_name', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('attribute_sort_order', sa.Integer(), nullable=True),
    sa.Column('value_text', sa.String(length=2048), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('display_value', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    schema='ecom_product',
    info={'is_view': True}
    )
    op.create_table('supplier_profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_address', sa.String(length=1024), nullable=True),
    sa.Column('tax_id', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('_realm', sa.String(length=255), nullable=True),
    sa.Column('_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_creator', sa.UUID(), nullable=True),
    sa.Column('_updater', sa.UUID(), nullable=True),
    sa.Column('_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_etag', sa.String(length=64), server_default=sa.text('uuid_generate_v4()::varchar'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['ecom_client.profile._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('profile_id'),
    schema='ecom_client'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_profile', schema='ecom_client')
    op.drop_table('_product_spec_detail', schema='ecom_product')
    op.drop_table('_product_review_list', schema='ecom_product')
    op.drop_table('_product_list', schema='ecom_product')
    op.drop_table('_product_detail', schema='ecom_product')
    op.drop_table('_product_category_list', schema='ecom_product')
    op.drop_table('_product_brand_line_list', schema='ecom_product')
    op.drop_table('role', schema='ecom_client')
    # ### end Alembic commands ###
